### ISSUE TITLE
Support SSLMODE verify-ca and verify-full

### ISSUE THREAD

**Issue by rlaveycal** [malthe/ts-postgres#112]
As per https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLMODE `verify-ca` and `verify-full` are missing from the `SSLMode` enum.

**Comment by malthe** [comment]
Yes – and that's because they're hard to understand and don't really play well with how secure connections are established using Node's [tls module](https://nodejs.org/api/tls.html).

So either you disable SSL, or you either prefer it or require it – in which case it will always verify the certificate. The only way to tweak that verification is to use environment variables `NODE_EXTRA_CA_CERTS=<your pub cert>` or `NODE_TLS_REJECT_UNAUTHORIZED=0` (not recommended).

It's intentional that you can't change that using the API in this package.

**Comment by rlaveycal** [comment]
My connection code is

```ts
    let options: Configuration | undefined = undefined
    if (process.env.PGSSLROOTCERT) {
        options = {
            ssl: {
                mode: SSLMode.Require,
                options: {
                    ca: fs.readFileSync(process.env.PGSSLROOTCERT!).toString(),
                },
            },
        }
    }

    const client = await connect(options)
```

to support self-signed certs which works great. I'd like to share the `PGSSLMODE` env var with other projects that do allow these values but the enum validation check blows up. I did try changing `process.env.PGSSLMODE` within the above but it didn't work.

It's not a big issue but if the enum validation were done only if `config.ssl` wasn't defined then all would be good.

**Comment by malthe** [comment]
The code to determine this is actually pretty cryptic but the documentation says the default behavior if you don't define `config.ssl` is to _prefer_ a secure connection – which is probably good because you'll benefit from things just working.

I think you want to try and look at `NODE_EXTRA_CA_CERTS` instead, it'll make your configuration go away entirely.
