### ISSUE TITLE
TypeError : Do not know how to serialize a BigInt 

### ISSUE THREAD

**Issue by hidhayaths** [malthe/ts-postgres#42]
While running a simple query using client.query('select * from table') method, I am receiving this error; please help

**Comment by malthe** [comment]
Now, `ts-postgres` supports bigints since version 1.1.3, but you'll get into trouble if you try to serialize them as a JSON object.

What you can try instead is to do a type-cast from your query, or in your program:

1. To type-cast, use `select some_big_int_column::int, ... from table`.
2. Client-side, just `Number(row["some_big_int_column"])`.
